name: 'Terraform'

on:
  pull_request:
   branches:
    - staging
   paths:
      - admin/**

jobs:
  packer_validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin
    steps:
      - uses: actions/checkout@v1
      - name: packer build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_private_key_file: ${{ secrets.ssh_private_key_file }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          ls
          pwd
          echo $ssh_private_key_file
          echo $ssh_private_key_file > staging.pem
          chmod 600 staging.pem
          packer build packer-admin.json